name: nikita/my-file-reference
typeName: 2
fields:
  - identifier: basic
    type: Palette
    label: LLL:EXT:core/Resources/Private/Language/locallang_tca.xlf:sys_file_reference.imageoverlayPalette
    fields:
      - identifier: alternative
        useExistingField: true
      - identifier: description
        useExistingField: true
      - type: Linebreak
      - identifier: link
        useExistingField: true
      - identifier: title
        useExistingField: true
      - type: Linebreak
      - identifier: custom_field
        type: Text
        label: My custom Field
      - type: Linebreak
      - identifier: crop
        useExistingField: true
